Migrate wiki documentation to github
jenkinsci/favorite-plugin pull request #59
Opened 2021-08-27 15:35 UTC by zbynek

This is a copy of #29 with merge conflicts resolved

CC @Yunir @olamy

2021-08-29 10:57 UTC, olamy requested changes

2021-08-29 10:57 UTC, olamy commented on CHANGELOG.md
> +
maybe a note here saying new release will be in github releases?

2021-08-30 06:25 UTC, olamy commented
#29 should be closed?

2021-08-30 06:51 UTC, zbynek commented
@olamy yes, please close #29

2021-08-30 06:53 UTC, merged